### ISSUE TITLE
Support emitting default values in JSON

### ISSUE THREAD

**Issue by philipithomas** [grpc-ecosystem/grpc-gateway#233]
Right now, `github.com/golang/protobuf` hardcodes `omitempty`, and the gateway does not support a way to enable the `EmitDefaults` option in 

This produces unintended behavior - like all false booleans or zero integers being omitted from JSON apis. I don't think it's wise to assume that API consumers know that the absence of a response parameter means that it is a specific empty value. 

I'm opening this issue for tracking - I'm not sure what the best solution is at this time though.

**Comment by philipithomas** [comment]
I was able to implement this using the `WithMarshalerOption` like this:

```
gwmux := runtime.NewServeMux(runtime.WithMarshalerOption(runtime.MIMEWildcard, &runtime.JSONPb{OrigName: true, EmitDefaults: true}))

```
I think this  behavior is a hurdle and unexpected behavior for new users of this system. 

I propose one of two changes:

1) Explicit documentation in the README of this behavior, including documentation for how to override it

2) Changing the default marshaler to include `EmitDefaults`. 

What is opinion here?

**Comment by achew22** [comment]
I think I'm comfortable with your first suggested solution. Let's not do anything without getting thoughts from @yugui. What do you think?

**Comment by philipithomas** [comment]
@yugui Wanted to follow up on this - what are your thoughts?

**Comment by yugui** [comment]
Sorry for my late reply.
Although it breaks compatibility, I still prefer the option (2) because it is more commonly used in REST APIs and we still keep a way to disable `EmitDefaults`.
I'm happy to review such a PR.

**Comment by jinleileiking** [comment]
Not Merged?

**Comment by jinleileiking** [comment]
@philipithomas 

```
gwmux := runtime.NewServeMux(runtime.WithMarshalerOption(runtime.MIMEWildcard, &runtime.JSONPb{OrigName: true, EmitDefaults: true}))
```

very, very useful!

**Comment by achew22** [comment]
This is now fixed

**Comment by dhrp** [comment]
@achew22, @philipithomas I believe somehow @achew22 's commit for EmitEmpty has dropped out. 

I was trying it and it doesn't work. I you look at the code changes in https://github.com/grpc-ecosystem/grpc-gateway/pull/145/files you'll notice there is no mention of 'Emit' anywhere. So perhaps it got lost rebasing or something?

**Comment by ornithocoder** [comment]
Hi there! Any progress on this one? I see the issue closed but #242 isn't merged yet. My team would love to see this one merged to simplify our interfaces and reduce boilerplate code on clients. Thank you!

**Comment by achew22** [comment]
Ah, I see what happened here. I was mistaken to close this -- my bad. Unfortunately there hasn't been progress.

@ornithocoder, if you were to extend the work and fix the tests I would be more than happy to merge it as soon as it goes green. It's just a little bit of test cleanup required.

**Comment by ornithocoder** [comment]
Hi @philipithomas / @achew22, here's part of the patch for the tests. It doesn't fix all the tests, tho. `client_test.go` and `integration_test.go` still have to be fixed.

```diff
diff --git a/examples/browser/a_bit_of_everything_service.spec.js b/examples/browser/a_bit_of_everything_service.spec.js
index edcbebe..f99c867 100644
--- a/examples/browser/a_bit_of_everything_service.spec.js
+++ b/examples/browser/a_bit_of_everything_service.spec.js
@@ -34,6 +34,15 @@ describe('ABitOfEverythingService', function() {
       sint32_value: 2147483647,
       sint64_value: "4611686018427387903",
       nonConventionalNameValue: "camelCase",
+      single_nested: null,
+      nested: [  ],
+      enum_value: "ZERO",
+      repeated_string_value: [  ],
+      map_value: Object({  }),
+      mapped_string_value: Object({  }),
+      mapped_nested_value: Object({  }),
+      timestamp_value: null,
+      repeated_enum_value: [  ],
     };
 
     beforeEach(function(done) {
@@ -72,10 +81,9 @@ describe('ABitOfEverythingService', function() {
       sint32_value: 2147483647,
       sint64_value: "4611686018427387903",
       nonConventionalNameValue: "camelCase",
-
       nested: [
-       { name: "bar", amount: 10 },
-       { name: "baz", amount: 20 },
+       { name: "bar", amount: 10, ok: 'FALSE' },
+       { name: "baz", amount: 20, ok: 'FALSE' },
       ],
       repeated_string_value: ["a", "b", "c"],
       oneof_string: "x",
@@ -83,9 +91,13 @@ describe('ABitOfEverythingService', function() {
       map_value: { a: 1, b: 2 },
       mapped_string_value: { a: "x", b: "y" },
       mapped_nested_value: {
-        a: { name: "x", amount: 1 },
-        b: { name: "y", amount: 2 },
+        a: { name: "x", amount: 1, ok: 'FALSE' },
+        b: { name: "y", amount: 2, ok: 'FALSE' },
       },
+      single_nested: null,
+      enum_value: "ZERO",
+      timestamp_value: null,
+      repeated_enum_value: [  ],
     };
 
     beforeEach(function(done) {
diff --git a/examples/browser/echo_service.spec.js b/examples/browser/echo_service.spec.js
index 97888c3..eca49f9 100644
--- a/examples/browser/echo_service.spec.js
+++ b/examples/browser/echo_service.spec.js
@@ -21,7 +21,7 @@ describe('EchoService', function() {
           {id: "foo"},
           {responseContentType: "application/json"}
       ).then(function(resp) {
-        expect(resp.obj).toEqual({id: "foo"});
+        expect(resp.obj).toEqual({id: "foo", num: '0'});
       }).catch(function(err) {
         done.fail(err);
       }).then(done);
@@ -34,7 +34,7 @@ describe('EchoService', function() {
           {body: {id: "foo"}},
           {responseContentType: "application/json"}
       ).then(function(resp) {
-        expect(resp.obj).toEqual({id: "foo"});
+        expect(resp.obj).toEqual({id: "foo", num: '0'});
       }).catch(function(err) {
         done.fail(err);
       }).then(done);
```

**Comment by johanbrandhorst** [comment]
This is part of the v2 work in #546.

**Comment by johanbrandhorst** [comment]
We want to support this  in v2

**Comment by johanbrandhorst** [comment]
This was merged with #1377

**Comment by seanlaff** [comment]
Would it make sense to mark all fields in the generated swagger `required: true` when this flag is enabled? As of now the swagger shows every field in a response as optional, which means any code (eg typescript) generated from the swagger requires null-checking fields that can't ever be null.

Seems like it may be challenging to do given people use the same message in both request/response, in which case the swagger generator would need to generate 2 schemas (unless there is a way for an _Operation_ to say its response fields are all required, but I am doubtful that exists).

**Comment by johanbrandhorst** [comment]
In proto3 all fields are required by default. Nullability is explicit using the `optional` keyword. I don't think the semantics translate cleanly to OpenAPI unfortunately (we've gone back and forth on this) so I don't want to make any behavioural changes at this point.
