### ISSUE TITLE
url query parameters should support semicolon in value field

### ISSUE THREAD

**Issue by ch3rub1m** [grpc-ecosystem/grpc-gateway#680]
I want reference to [Core Reporting API: Filters](https://developers.google.com/analytics/devguides/reporting/core/v3/reference#filters) to implement the filter spec defined in [Google API Design Guide](https://cloud.google.com/apis/design/standard_fields.).

In this case, semicolons are used to indicate operator `AND`.
However, it disappeared with the string behind it when using grpc-gateway . It seems like be treated as the character `&`.
However, if I request without grpc-gateway, it works.
I think it shouldn't be treated differently in grpc and grpc-gateway.

**Comment by achew22** [comment]
I think this is fixed by #660

**Comment by ch3rub1m** [comment]
@achew22 Thanks for quick reply. I am using the `dep` and run the `dep ensure -update` but It looks like this fix was not yet released. Could you give some advices about how to use the latest code in the project?

**Comment by achew22** [comment]
You can pull from that repo instead and try it out or git pull from it in
$GOPATH/src/...

**Comment by ch3rub1m** [comment]
@achew22 Hi, I tried but it still failed. It seems like #660 didn't fix this issue.

**Comment by achew22** [comment]
Can you elaborate on this and explain what you tried and why it didn't fix
the issue?

**Comment by ch3rub1m** [comment]
@achew22 I read the source code and I found the issue is caused by `gengateway/template.go`, it calls the method `req.URL.Query()` directly. In this method, package `req` split query parameters with both `&` and `;`. So I encode the `;` to `%3B` when request and it works. Thank you for your help.
